import * as XLSX from 'xlsx';
import type { DashboardSummary, ReportRecord } from '@/core/types/domain';
import { formatDateTime } from '@/shared/utils/format';

export const exportReportToExcel = (
  report: ReportRecord,
  wardOverview?: DashboardSummary['wardOverview'],
) => {
  const workbook = XLSX.utils.book_new();

  const summaryRows = [
    ['Field', 'Value'],
    ['Report Name', report.name],
    ['Period', report.periodLabel],
    ['Status', report.status],
    ['Generated At', report.generatedAt ? formatDateTime(report.generatedAt) : 'Not generated'],
    ['Generated By', report.generatedBy ?? '—'],
    ['Approved At', report.approvedAt ? formatDateTime(report.approvedAt) : '—'],
    ['Approved By', report.approvedBy ?? '—'],
    ['Sign-off Required', report.signOffRequired ? 'Yes' : 'No'],
    ['Signed Off At', report.signedOffAt ? formatDateTime(report.signedOffAt) : '—'],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 20 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Report Summary');

  if (wardOverview && wardOverview.length > 0) {
    const wardRows = [
      ['Ward', 'Active Complaints', 'Weighbridge Trips', 'Flagged Records'],
      ...wardOverview.map((ward) => [
        ward.wardId.toUpperCase(),
        ward.complaintCount,
        ward.weighbridgeTrips,
        ward.flaggedRecords,
      ]),
    ];
    const wardSheet = XLSX.utils.aoa_to_sheet(wardRows);
    wardSheet['!cols'] = [{ wch: 12 }, { wch: 18 }, { wch: 18 }, { wch: 16 }];
    XLSX.utils.book_append_sheet(workbook, wardSheet, 'Ward Summary');
  }

  const fileName = `${report.name}_${report.periodLabel}.xlsx`.replace(/[^a-zA-Z0-9_.]+/g, '_');
  XLSX.writeFile(workbook, fileName);
};
